In [37]:
pip install pdfplumber pandas openpyxl

Collecting pdfplumber
  Downloading pdfplumber-0.11.3-py3-none-any.whl.metadata (41 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 42.0/42.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (2.1.4)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.10/dist-packages (3.1.5)
Collecting pdfminer.six==20231228 (from pdfplumber)
  Downloading pdfminer.six-20231228-py3-none-any.whl.metadata (4.2 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.10/dist-packages (from pdfplumber) (9.4.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-4.30.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (48 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 48.5/48.5 kB 2.5 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six==20231228->pdfplumber) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six==20231228->pdfplumber) (42.0.8)
Requirement already satisfied: numpy<2,>=1.22.4 in /usr/local/lib/python3.10/dist-packages (from pandas) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.1 in /usr/local/lib/python3.10/dist-packages (from pandas) (2024.1)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl) (1.1.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (1.17.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20231228->pdfplumber) (2.22)
Downloading pdfplumber-0.11.3-py3-none-any.whl (59 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 59.2/59.2 kB 2.6 MB/s eta 0:00:00
Downloading pdfminer.six-20231228-py3-none-any.whl (5.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 54.1 MB/s eta 0:00:00
Downloading pypdfium2-4.30.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.8 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.8/2.8 MB 55.6 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20231228 pdfplumber-0.11.3 pypdfium2-4.30.0

In [39]:
import pdfplumber
import pandas as pd


with pdfplumber.open("/content/UP.pdf") as pdf:
    all_pages_data = []


    for page in pdf.pages:
        table = page.extract_table()
        if table:
            all_pages_data.extend(table)

if all_pages_data:
    df = pd.DataFrame(all_pages_data[1:], columns=all_pages_data[0])
    df.to_excel("file.xlsx", index=False)
else:
    print("No table data found in the PDF.")

In [5]:
import pandas as pd
ds=pd.read_excel("/content/file.xlsx")
ds

,Sr.\nNO,Name of Cold Storage,Category\n(Gen/OB\nC/SC/ST),Full Address,District,Type of\nunit(New/Exp.\n/Ren/OG),Financing\nBank,Financing\nBranch,Year (with date) of\nsanction,Capacity (MT),Project\nCost\n(Rs.Lakh),Eligible\nsubsidy,Amount of\nAdvance\nsubsidy\nreleased\n(Rs.lakh),Amount of\nFinal\nSubsidy\n(Rs.lakh),Total\nSubsidy\n(Rs.lakh)
0,1,Akshita and Antriksha cold\nstorage,NaN,Meerut,Meerut,New Unit,Corpn. bank,Meerut,06/21/00,8842.000,250.790,50.000,25.000,0.000,25.000
1,2,Ahuja cold storage,NaN,Unnao,Unnao,New Unit,PNB,Unnao,09/20/00,9800.000,252.102,50.000,25.000,0.000,25.000
2,3,Maya shitalayaPvt Ltd,NaN,Unnao,Unnao,Expansion,PNB,Unnao,"August 21, 2000",4485.370,105.870,26.468,13.230,13.233,26.463
3,4,Adarsh Satendra cold sto. &\nallied Indust.,NaN,Lucknow,Lucknow,New Unit,PNB,Lucknow,"June 14, 2000",6881.000,210.050,50.000,25.000,NaN,25.000
4,5,H C Garg Ice & Cold Storage,NaN,Agra,Agra,Expansion,Canara Bank,Agra,"September 9, 2002",3931.200,79.000,19.750,9.875,6.397,16.272
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
915,916,M/s Shalimar Cold Storage & Ice\nFactory,Gen,"Rujihat, Mauaima,\nSoraon, Allahabad",Allahabad,New,Bank of\nBaroda,"Bank of Baroda,\nP.D. Tandon\nRoad, Allahabad,",28.08.2012,5130.825,204.100,49.724,0.000,49.724,49.724
916,917,M/s Shiva Sheetgrah (P) Ltd,NaN,"Birahimpur,\nSaurikh Road,\nChhibramau,\nKannauj",Kannauj,New,Bank of\nBaroda,"Kabari Market\nBranch, 122/707,\nParas Bhawan,...",NaN,5555.488,222.526,50.000,0.000,NaN,0.000
917,918,Doaba Sheetgrah,NaN,"85A/108,\nMeerapatti,",Allahabad,Modernisation,Union Bank of\nIndia,"BMJH Preetam\nNagar Branch,",NaN,NaN,NaN,NaN,NaN,NaN,0.000
918,919,M/s Devta Cold Storage,NaN,"Makhanpur,\nFirozabad",Firozabad,NaN,UCO Bank,Firozabad,NaN,NaN,NaN,NaN,NaN,NaN,0.000
919,920,JMD Cold Storage & Ice Factory,NaN,"Dadauli, Soraon",Allahabad,New,Allahabad\nBank,"Civil Lines Branch,\nAllahabad",NaN,NaN,252.750,NaN,NaN,NaN,0.000

In [6]:
ds.shape

(920, 15)

In [7]:
ds.isna().sum()

Sr.\nNO                                               0
Name of Cold Storage                                  0
Category\n(Gen/OB\nC/SC/ST)                         801
Full Address                                          2
District                                              1
Type of\nunit(New/Exp.\n/Ren/OG)                      6
Financing\nBank                                       3
Financing\nBranch                                     4
Year (with date) of\nsanction                        66
Capacity (MT)                                        55
Project\nCost\n(Rs.Lakh)                             53
Eligible\nsubsidy                                    56
Amount of\nAdvance\nsubsidy\nreleased\n(Rs.lakh)     18
Amount of\nFinal\nSubsidy\n(Rs.lakh)                327
Total\nSubsidy\n(Rs.lakh)                             0
dtype: int64

In [8]:
ds.columns = [
    'Sr_No', 'Name', 'Category', 'Full_Address', 'District',
    'Type_of_Unit', 'Financing_Bank', 'Financing_Branch', 'Year_of_Sanction',
    'Capacity_MT', 'Project_Cost_Rs_Lakh', 'Eligible_Subsidy',
    'Advance_Subsidy_Rs_Lakh', 'Final_Subsidy_Rs_Lakh', 'Total_Subsidy_Rs_Lakh'
]

In [9]:
columns_to_drop = ['Sr_No', 'Category', 'Financing_Bank', 'Financing_Branch',
                   'Eligible_Subsidy', 'Advance_Subsidy_Rs_Lakh',
                   'Final_Subsidy_Rs_Lakh', 'Total_Subsidy_Rs_Lakh']
data_cleaned = ds.drop(columns=columns_to_drop)

In [10]:
data_cleaned = data_cleaned.drop_duplicates(subset='Name', keep='first')

In [11]:
data_cleaned['Capacity_MT'] = pd.to_numeric(data_cleaned['Capacity_MT'], errors='coerce')
data_cleaned['Year_of_Sanction'] = pd.to_datetime(data_cleaned['Year_of_Sanction'], errors='coerce')

<ipython-input-11-2a4f76e89281>:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  data_cleaned['Year_of_Sanction'] = pd.to_datetime(data_cleaned['Year_of_Sanction'], errors='coerce')

In [13]:
data_cleaned['Full_Address'] = data_cleaned['Full_Address'].fillna('Unknown')
data_cleaned['District'] = data_cleaned['District'].fillna('Unknown')

In [19]:
data_cleaned.to_excel('cleaned_cold_storage_data.xlsx', index=False)

In [20]:
data_cleaned

,Name,Full_Address,District,Type_of_Unit,Year_of_Sanction,Capacity_MT,Project_Cost_Rs_Lakh
0,Akshita and Antriksha cold\nstorage,Meerut,Meerut,New Unit,2000-06-21,8842.000,250.790
1,Ahuja cold storage,Unnao,Unnao,New Unit,2000-09-20,9800.000,252.102
2,Maya shitalayaPvt Ltd,Unnao,Unnao,Expansion,2000-08-21,4485.370,105.870
3,Adarsh Satendra cold sto. &\nallied Indust.,Lucknow,Lucknow,New Unit,2000-06-14,6881.000,210.050
4,H C Garg Ice & Cold Storage,Agra,Agra,Expansion,2002-09-09,3931.200,79.000
...,...,...,...,...,...,...,...
915,M/s Shalimar Cold Storage & Ice\nFactory,"Rujihat, Mauaima,\nSoraon, Allahabad",Allahabad,New,2012-08-28,5130.825,204.100
916,M/s Shiva Sheetgrah (P) Ltd,"Birahimpur,\nSaurikh Road,\nChhibramau,\nKannauj",Kannauj,New,NaT,5555.488,222.526
917,Doaba Sheetgrah,"85A/108,\nMeerapatti,",Allahabad,Modernisation,NaT,NaN,NaN
918,M/s Devta Cold Storage,"Makhanpur,\nFirozabad",Firozabad,NaN,NaT,NaN,NaN
919,JMD Cold Storage & Ice Factory,"Dadauli, Soraon",Allahabad,New,NaT,NaN,252.750

In [17]:
data_cleaned.shape

(895, 7)

In [18]:
data_cleaned.isna().sum()

Name                     0
Full_Address             0
District                 0
Type_of_Unit             6
Year_of_Sanction        66
Capacity_MT             53
Project_Cost_Rs_Lakh    51
dtype: int64

In [21]:
data_cleaned['Capacity_MT'].fillna(data_cleaned['Capacity_MT'].mean(), inplace=True)
data_cleaned['Project_Cost_Rs_Lakh'].fillna(data_cleaned['Project_Cost_Rs_Lakh'].median(), inplace=True)

In [22]:
data_cleaned['Type_of_Unit'].fillna('Unknown', inplace=True)

In [23]:
data_cleaned.fillna(method='ffill', inplace=True)

<ipython-input-23-30daba33e945>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data_cleaned.fillna(method='ffill', inplace=True)

In [25]:
data_cleaned.isna().sum()

Name                    0
Full_Address            0
District                0
Type_of_Unit            0
Year_of_Sanction        0
Capacity_MT             0
Project_Cost_Rs_Lakh    0
dtype: int64

In [26]:
data_cleaned.shape

(895, 7)

In [28]:
data_cleaned

,Name,Full_Address,District,Type_of_Unit,Year_of_Sanction,Capacity_MT,Project_Cost_Rs_Lakh
0,Akshita and Antriksha cold\nstorage,Meerut,Meerut,New Unit,2000-06-21,8842.000000,250.790
1,Ahuja cold storage,Unnao,Unnao,New Unit,2000-09-20,9800.000000,252.102
2,Maya shitalayaPvt Ltd,Unnao,Unnao,Expansion,2000-08-21,4485.370000,105.870
3,Adarsh Satendra cold sto. &\nallied Indust.,Lucknow,Lucknow,New Unit,2000-06-14,6881.000000,210.050
4,H C Garg Ice & Cold Storage,Agra,Agra,Expansion,2002-09-09,3931.200000,79.000
...,...,...,...,...,...,...,...
915,M/s Shalimar Cold Storage & Ice\nFactory,"Rujihat, Mauaima,\nSoraon, Allahabad",Allahabad,New,2012-08-28,5130.825000,204.100
916,M/s Shiva Sheetgrah (P) Ltd,"Birahimpur,\nSaurikh Road,\nChhibramau,\nKannauj",Kannauj,New,2012-08-28,5555.488000,222.526
917,Doaba Sheetgrah,"85A/108,\nMeerapatti,",Allahabad,Modernisation,2012-08-28,14088.967931,190.875
918,M/s Devta Cold Storage,"Makhanpur,\nFirozabad",Firozabad,Unknown,2012-08-28,14088.967931,190.875
919,JMD Cold Storage & Ice Factory,"Dadauli, Soraon",Allahabad,New,2012-08-28,14088.967931,252.750

In [29]:
pip install geopy folium

Requirement already satisfied: geopy in /usr/local/lib/python3.10/dist-packages (2.4.1)
Requirement already satisfied: folium in /usr/local/lib/python3.10/dist-packages (0.17.0)
Requirement already satisfied: geographiclib<3,>=1.52 in /usr/local/lib/python3.10/dist-packages (from geopy) (2.0)
Requirement already satisfied: branca>=0.6.0 in /usr/local/lib/python3.10/dist-packages (from folium) (0.7.2)
Requirement already satisfied: jinja2>=2.9 in /usr/local/lib/python3.10/dist-packages (from folium) (3.1.4)
Requirement already satisfied: numpy in /usr/local/lib/python3.10/dist-packages (from folium) (1.26.4)
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from folium) (2.32.3)
Requirement already satisfied: xyzservices in /usr/local/lib/python3.10/dist-packages (from folium) (2024.6.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from jinja2>=2.9->folium) (2.1.5)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (2.0.7)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests->folium) (2024.7.4)

In [30]:
from geopy.geocoders import Nominatim
import pandas as pd
import time

geolocator = Nominatim(user_agent="cold_storage_locator")


def geocode_address(address):
    try:
        location = geolocator.geocode(address)
        return location.latitude, location.longitude
    except:
        return None, None


data_cleaned['Latitude'], data_cleaned['Longitude'] = zip(*data_cleaned['Full_Address'].apply(geocode_address))
data_cleaned.to_excel('geocoded_cold_storage_data.xlsx', index=False)

WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Jalalpur+Panwara%2C%0AG.T.+Road%2C%0AKannauj&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Vill%3A+Sahpau%2C%0AHathras&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Babatpur%2C%0AVaranasi&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=C-18%2CFoundry%0ANagar%2C+Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=C-1+to+C-3%2C+C-12+to%0AC-14%2C+Industrila%0AEstate%2C+Firozabad&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=167-A%2C+Station%0ARoad%2C+Etawah&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=C-4+to+C-9%2C%0ABachhrawan%0AIndustrial+Estate%2C%0ABachhrawan%2C&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Plot%3A+BL+2B+and+3%2C%0ASector+13%2C%0AG.I.D.A.%2C%0AGorakhpur&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=E-18%2C+Foundry%0ANagar%2C+Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Kh.No.1320%2C+1321-%0APili+Pokhar%2C%0AHathras+Road%2C&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Kh+No.+305%2C%0AMohalla+Tola%2C+Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Khasra%0ANo.1826%2C2035%2C203%0A2%2C2034%2C2036%2C%0AMauza+Poiya%2C%0ANagla+Asha%2C&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Khasra+No.1691+%26%0A1692%2C+Mauza%0AAwagarh%2C+Jalesar%2C%0AEtah&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Khasra+No.1432+%26%0A1433+1845+Gram%0APost+Poiya+Tehsil%0AEtmadpur&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Khasra+No.1432+%26%0A1433+1845+Gram%0APost+Poiya+Tehsil%0AEtmadpur&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Khasra+No.221%0AMauza+Partappur%2C%0AFatehabad%2C+Agra&format=json&limit=1
WARNING:urllib3.connectionpool:Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ReadTimeoutError("HTTPSConnectionPool(host='nominatim.openstreetmap.org', port=443): Read timed out. (read timeout=1)")': /search?q=Khasra+No.453%2C%0A454+Mauza%0ABhadrauli%2C+Pinahat%0ARoad%2C+Tehsil+Bag%2C&format=json&limit=1

In [33]:
data_cleaned

,Name,Full_Address,District,Type_of_Unit,Year_of_Sanction,Capacity_MT,Project_Cost_Rs_Lakh,Latitude,Longitude
0,Akshita and Antriksha cold\nstorage,Meerut,Meerut,New Unit,2000-06-21,8842.000000,250.790,29.001856,77.767967
1,Ahuja cold storage,Unnao,Unnao,New Unit,2000-09-20,9800.000000,252.102,26.567326,80.619819
2,Maya shitalayaPvt Ltd,Unnao,Unnao,Expansion,2000-08-21,4485.370000,105.870,26.567326,80.619819
3,Adarsh Satendra cold sto. &\nallied Indust.,Lucknow,Lucknow,New Unit,2000-06-14,6881.000000,210.050,26.838100,80.934600
4,H C Garg Ice & Cold Storage,Agra,Agra,Expansion,2002-09-09,3931.200000,79.000,27.175255,78.009816
...,...,...,...,...,...,...,...,...,...
915,M/s Shalimar Cold Storage & Ice\nFactory,"Rujihat, Mauaima,\nSoraon, Allahabad",Allahabad,New,2012-08-28,5130.825000,204.100,NaN,NaN
916,M/s Shiva Sheetgrah (P) Ltd,"Birahimpur,\nSaurikh Road,\nChhibramau,\nKannauj",Kannauj,New,2012-08-28,5555.488000,222.526,NaN,NaN
917,Doaba Sheetgrah,"85A/108,\nMeerapatti,",Allahabad,Modernisation,2012-08-28,14088.967931,190.875,NaN,NaN
918,M/s Devta Cold Storage,"Makhanpur,\nFirozabad",Firozabad,Unknown,2012-08-28,14088.967931,190.875,NaN,NaN
919,JMD Cold Storage & Ice Factory,"Dadauli, Soraon",Allahabad,New,2012-08-28,14088.967931,252.750,NaN,NaN

In [31]:
import folium

map_center = [data_cleaned['Latitude'].mean(), data_cleaned['Longitude'].mean()]
m = folium.Map(location=map_center, zoom_start=6)

for i, row in data_cleaned.iterrows():
    if pd.notna(row['Latitude']) and pd.notna(row['Longitude']):
        folium.Marker(
            location=[row['Latitude'], row['Longitude']],
            popup=f"{row['Name']} ({row['Capacity_MT']} MT)",
        ).add_to(m)
m.save('cold_storage_map.html')

# Capacity Distribution: Using Different Marker Colors or Sizes

In [34]:

m = folium.Map(location=map_center, zoom_start=6)

def get_color(capacity):
    if capacity < 5000:
        return 'green'
    elif 5000 <= capacity < 10000:
        return 'orange'
    else:
        return 'red'

for i, row in data_cleaned.iterrows():
    if pd.notna(row['Latitude']) and pd.notna(row['Longitude']):
        folium.CircleMarker(
            location=[row['Latitude'], row['Longitude']],
            radius=row['Capacity_MT'] / 1000,
            color=get_color(row['Capacity_MT']),
            fill=True,
            fill_color=get_color(row['Capacity_MT']),
            popup=f"{row['Name']} ({row['Capacity_MT']} MT)",
        ).add_to(m)

m.save('cold_storage_capacity_map.html')

# Cluster Analysis: Identifying Regions with High Concentration of Cold Storages

In [35]:
import folium
from folium.plugins import MarkerCluster

map_center = [data_cleaned['Latitude'].mean(), data_cleaned['Longitude'].mean()]
m = folium.Map(location=map_center, zoom_start=6)
marker_cluster = MarkerCluster().add_to(m)

for i, row in data_cleaned.iterrows():
    if pd.notna(row['Latitude']) and pd.notna(row['Longitude']):
        folium.Marker(
            location=[row['Latitude'], row['Longitude']],
            popup=f"{row['Name']} ({row['Capacity_MT']} MT)",
        ).add_to(marker_cluster)
m.save('cold_storage_cluster_map.html')